// Generated by CoffeeScript 2.0.0-dev
void function () {
  var Bar;
  Bar = function () {
    function Bar() {
    }
    Bar.prototype.bar = function () {
      return 'Bar!';
    };
    return Bar;
  }();
}.call(this);
