// Generated by CoffeeScript 2.0.0-dev
void function () {
  var Foo;
  Foo = function () {
    function Foo() {
    }
    Foo.prototype.foo = function () {
      return 'Foo!';
    };
    return Foo;
  }();
}.call(this);
